### ISSUE TITLE
Nit request: Make tokens always truthy

### ISSUE THREAD

**Issue by sclaxton** [rwjblue/ember-test-waiters#110]
https://github.com/rwjblue/ember-test-waiters/blob/1a09a527d6261385d390d056a2b985074b74fc97/addon/test-waiter.ts#L4

Can we have token enumeration start from `1`? Just got trolled checking if a token existed or not using a simple `if (token) {}` check and it didn't work cause it was `0`...

**Comment by scalvert** [comment]
This seems entirely reasonable. It's hard to know that the properties of the first token are effectively different from the rest without knowing it's a number.

**Comment by scalvert** [comment]
Closed via #111
