### ISSUE TITLE
CI test timeout

### ISSUE THREAD

**Issue by bobisjan** [rwjblue/ember-test-waiters#16]
Hi,

CI for `ember-web-app` is failing now, because test timeout https://travis-ci.org/zonkyio/ember-web-app/jobs/567242322.

The [registration](https://github.com/rwjblue/ember-test-waiters/blob/master/addon/waiter-manager.ts#L16) of legacy test waiter is causing tests to timeout, because it expects `true` if there are no pending tasks, but [hasPendingWaiters()](https://github.com/rwjblue/ember-test-waiters/blob/master/addon/waiter-manager.ts#L92) returns `true`, when it has some pending tasks to wait for.

**Comment by scalvert** [comment]
Fixed and published as `1.1.1`. 🎉 

Thanks for the PR!

**Comment by rwjblue** [comment]
Thank you for reporting (and fixing)!
