### ISSUE TITLE
API should merge with @ember/test-helpers

### ISSUE THREAD

**Issue by izelnakri** [rwjblue/ember-test-waiters#63]
Hi @rwjblue , I have quick but important question. Why do we need this package separately? 

Since this package is a hard dependency to `@ember/test-helpers`, can we merge this to `@ember/test-helpers` and provide the API & functionality there?

**Comment by scalvert** [comment]
Hey @izelnakri. Good question.

This package was meant to be used in application code, and as such it needs to be added as a `dependency` in our application. With this requirement, and if we merged this package into `@ember/test-helpers`, we'd require applications to add `@ember/test-helpers` as a `dependency` too, which doesn't make sense. 

So, this package makes sense from a standalone perspective, and is intended to be consumed by both applications _and_ `@ember/test-helpers`.

I hope this answer makes sense.

**Comment by izelnakri** [comment]
Hi @scalvert, thanks for your quick answer.

Im not convinced why the current structure is better. Why adding `@ember/test-helpers` as a dependency doesnt make any sense? As I stressed before all ember apps currently use this package via `ember-qunit` > `@ember/test-helpers` > `ember-test-waiters`. I strongly suggest we merge this code/package to `@ember/test-helpers` for coherence.

**Comment by rwjblue** [comment]
> As I stressed before all ember apps currently use this package via ember-qunit > @ember/test-helpers > ember-test-waiters.
 
You are correct, all apps have `@ember/test-helpers` as a transitive dependency, however it **does not ship** as part of a production application build. This addon provides test waiter functionality that we expect applications and addons will use directly in non-test code, and as such those imports/function invocations need to not throw errors (and be as small/light-weight as possible) in production.

**Comment by izelnakri** [comment]
Thanks for the explanation @scalvert , @rwjblue. Hopefully soon we'll have treeshaking so that we can remove the need for packages like this one.
